spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mockify
    username: mockify_user
    password: mockify_password

  jpa:
    show-sql: true

  docker:
    compose:
      enabled: true

jwt:
  secret: ${JWT_SECRET:af84c6a92b8d5f4e1c7d92a6e6a1c56a4e9f45bba782cd51e2e1f67a9c34b12f}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}